CREATE TABLE AllstarFull (
    playerID VARCHAR(9) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    gameNumber SMALLINT(6) NOT NULL CHECK(gameNumber >= 0),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    playedInGame SMALLINT(6) DEFAULT NULL CHECK(playedInGame IS NULL OR playedInGame = 0 OR playedInGame = 1),
    startingPosition SMALLINT(6) DEFAULT NULL CHECK(startingPosition IS NULL OR (startingPosition >= 1 AND startingPosition <= 10)),
    PRIMARY KEY (playerID, yearID, gameNumber),
    FOREIGN KEY (playerID) REFERENCES Players(playerID),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Appearances (
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    playerID VARCHAR(9) NOT NULL,
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    GS SMALLINT(6) DEFAULT NULL CHECK(GS IS NULL OR (GS >= 0 AND G IS NOT NULL AND GS <= G)),
    G_batting SMALLINT(6) DEFAULT NULL CHECK(G_batting IS NULL OR (G_batting >= 0 AND G IS NOT NULL AND G_batting <= G)),
    G_defense SMALLINT(6) DEFAULT NULL CHECK(G_defense IS NULL OR (G_defense >= 0 AND G IS NOT NULL AND G_defense <= G)),
    G_p SMALLINT(6) DEFAULT NULL CHECK(G_p IS NULL OR (G_p >= 0 AND G IS NOT NULL AND G_p <= G)),
    G_c SMALLINT(6) DEFAULT NULL CHECK(G_c IS NULL OR (G_c >= 0 AND G IS NOT NULL AND G_c <= G)),
    G_1b SMALLINT(6) DEFAULT NULL CHECK(G_1b IS NULL OR (G_1b >= 0 AND G IS NOT NULL AND G_1b <= G)),
    G_2b SMALLINT(6) DEFAULT NULL CHECK(G_2b IS NULL OR (G_2b >= 0 AND G IS NOT NULL AND G_2b <= G)),
    G_3b SMALLINT(6) DEFAULT NULL CHECK(G_3b IS NULL OR (G_3b >= 0 AND G IS NOT NULL AND G_3b <= G)),
    G_ss SMALLINT(6) DEFAULT NULL CHECK(G_ss IS NULL OR (G_ss >= 0 AND G IS NOT NULL AND G_ss <= G)),
    G_lf SMALLINT(6) DEFAULT NULL CHECK(G_lf IS NULL OR (G_lf >= 0 AND G IS NOT NULL AND G_lf <= G)),
    G_cf SMALLINT(6) DEFAULT NULL CHECK(G_cf IS NULL OR (G_cf >= 0 AND G IS NOT NULL AND G_cf <= G)),
    G_rf SMALLINT(6) DEFAULT NULL CHECK(G_rf IS NULL OR (G_rf >= 0 AND G IS NOT NULL AND G_rf <= G)),
    G_of SMALLINT(6) DEFAULT NULL CHECK(G_of IS NULL OR (G_of >= 0 AND G IS NOT NULL AND G_of <= G)),
    G_dh SMALLINT(6) DEFAULT NULL CHECK(G_dh IS NULL OR (G_dh >= 0 AND G IS NOT NULL AND G_dh <= G)),
    G_ph SMALLINT(6) DEFAULT NULL CHECK(G_ph IS NULL OR (G_ph >= 0 AND G IS NOT NULL AND G_ph <= G)),
    G_pr SMALLINT(6) DEFAULT NULL CHECK(G_pr IS NULL OR (G_pr >= 0 AND G IS NOT NULL AND G_pr <= G)),
    PRIMARY KEY (yearID, teamID, playerID),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE AwardsPlayers (
    playerID VARCHAR(9) NOT NULL,
    awardID VARCHAR(255) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    leagueID CHAR(2) NOT NULL, 
    didTie VARCHAR(1) DEFAULT NULL CHECK(didTie IS NULL OR didTie = 'Y'),
    note VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (playerID, awardID, yearID, leagueID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Batting (
    playerID VARCHAR(9) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    stint SMALLINT(6) NOT NULL CHECK(stint >= 1),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    AB SMALLINT(6) DEFAULT NULL CHECK(AB IS NULL OR AB >= 0),
    R SMALLINT(6) DEFAULT NULL CHECK(R IS NULL OR R >= 0),
    H SMALLINT(6) DEFAULT NULL CHECK(H IS NULL OR H >= 0),
    2B SMALLINT(6) DEFAULT NULL CHECK(2B IS NULL OR 2B >= 0),
    3B SMALLINT(6) DEFAULT NULL CHECK(3B IS NULL OR 3B >= 0),
    HR SMALLINT(6) DEFAULT NULL CHECK(HR IS NULL OR HR >= 0),
    RBI SMALLINT(6) DEFAULT NULL CHECK(RBI IS NULL OR RBI >= 0),
    SB SMALLINT(6) DEFAULT NULL CHECK(SB IS NULL OR SB >= 0),
    CS SMALLINT(6) DEFAULT NULL CHECK(CS IS NULL OR CS >= 0),
    BB SMALLINT(6) DEFAULT NULL CHECK(BB IS NULL OR BB >= 0),
    SO SMALLINT(6) DEFAULT NULL CHECK(SO IS NULL OR SO >= 0),
    IBB SMALLINT(6) DEFAULT NULL CHECK(IBB IS NULL OR IBB >= 0),
    HBP SMALLINT(6) DEFAULT NULL CHECK(HBP IS NULL OR HBP >= 0),
    SH SMALLINT(6) DEFAULT NULL CHECK(SH IS NULL OR SH >= 0),
    SF SMALLINT(6) DEFAULT NULL CHECK(SF IS NULL OR SF >= 0),
    GIDP SMALLINT(6) DEFAULT NULL CHECK(GIDP IS NULL OR GIDP >= 0),
    PRIMARY KEY (playerID, yearID, stint),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Fielding (
    playerID VARCHAR(9) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    stint SMALLINT(6) NOT NULL CHECK(stint >= 1),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    position VARCHAR(2) NOT NULL CHECK(position = 'P' OR position = 'C' OR position = '1B' OR position = '2B' OR position = '3B' OR position = 'SS' OR position = 'OF'),
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    GS SMALLINT(6) DEFAULT NULL CHECK(GS IS NULL OR (GS >= 0 AND G IS NOT NULL AND GS <= G)),
    outsRecorded SMALLINT(6) DEFAULT NULL CHECK(outsRecorded IS NULL OR outsRecorded >= 0),
    PO SMALLINT(6) DEFAULT NULL CHECK(PO IS NULL OR PO >= 0),
    A SMALLINT(6) DEFAULT NULL CHECK(A IS NULL OR A >= 0),
    E SMALLINT(6) DEFAULT NULL CHECK(E IS NULL OR E >= 0),
    DP SMALLINT(6) DEFAULT NULL CHECK(DP IS NULL OR DP >= 0),
    PB SMALLINT(6) DEFAULT NULL CHECK(PB IS NULL OR PB >= 0),
    WP SMALLINT(6) DEFAULT NULL CHECK(WP IS NULL OR WP >= 0),
    SB SMALLINT(6) DEFAULT NULL CHECK(SB IS NULL OR SB >= 0),
    CS SMALLINT(6) DEFAULT NULL CHECK(CS IS NULL OR CS >= 0),
    PRIMARY KEY (playerID, yearID, stint, position),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE FieldingOFSplit (
    playerID VARCHAR(9) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    stint SMALLINT(6) NOT NULL CHECK(stint >= 1),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    position VARCHAR(2) NOT NULL CHECK(position = 'LF' OR position = 'CF' OR position = 'RF'),
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    GS SMALLINT(6) DEFAULT NULL CHECK(GS IS NULL OR (GS >= 0 AND G IS NOT NULL AND GS <= G)),
    outsRecorded SMALLINT(6) DEFAULT NULL CHECK(outsRecorded IS NULL OR outsRecorded >= 0),
    PO SMALLINT(6) DEFAULT NULL CHECK(PO IS NULL OR PO >= 0),
    A SMALLINT(6) DEFAULT NULL CHECK(A IS NULL OR A >= 0),
    E SMALLINT(6) DEFAULT NULL CHECK(E IS NULL OR E >= 0),
    DP SMALLINT(6) DEFAULT NULL CHECK(DP IS NULL OR DP >= 0),
    PB SMALLINT(6) DEFAULT NULL CHECK(PB IS NULL OR PB >= 0),
    WP SMALLINT(6) DEFAULT NULL CHECK(WP IS NULL OR WP >= 0),
    SB SMALLINT(6) DEFAULT NULL CHECK(SB IS NULL OR SB >= 0),
    CS SMALLINT(6) DEFAULT NULL CHECK(CS IS NULL OR CS >= 0),
    PRIMARY KEY (playerID, yearID, stint, position),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (playerID) REFERENCES Player(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE HallOfFame (
    playerID VARCHAR(10) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    wasInducted VARCHAR(1) NOT NULL CHECK(wasInducted = 'N' OR wasInducted = 'Y'),
    PRIMARY KEY (playerID, yearID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE HomeGames (
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),          /* type change */
    leagueID CHAR(2) DEFAULT NULL,
    teamID CHAR(3) NOT NULL,              
    parkID VARCHAR(255) NOT NULL,              
    spanFirst VARCHAR(255) DEFAULT NULL,
    spanLast VARCHAR(255) DEFAULT NULL,
    gamesPlayedAtHome INT(11) DEFAULT NULL CHECK(gamesPlayedAtHome IS NULL OR gamesPlayedAtHome >= 0),
    gamesWithFans INT(11) DEFAULT NULL CHECK(gamesWithFans IS NULL OR (gamesWithFans >= 0 AND gamesPlayedAtHome IS NOT NULL AND gamesWithFans <= gamesPlayedAtHome)),
    totalAttendance INT(11) DEFAULT NULL CHECK(totalAttendance IS NULL OR totalAttendance >= 0),
    PRIMARY KEY (yearID, teamID, parkID),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (parkID) REFERENCES Parks(parkID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Parks (
    parkAlias VARCHAR(255) DEFAULT NULL,
    parkID VARCHAR(255) NOT NULL,
    parkName VARCHAR(255) DEFAULT NULL,
    city VARCHAR(255) DEFAULT NULL,
    state VARCHAR(255) DEFAULT NULL,
    country VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (parkID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Players (
    playerID VARCHAR(9) NOT NULL,
    birthYear INT(11) DEFAULT NULL CHECK(birthYear IS NULL OR birthYear >= 1851),
    birthMonth INT(11) DEFAULT NULL CHECK(birthMonth IS NULL OR (birthMonth >= 1 AND birthMonth <= 12)),
    birthDay INT(11) DEFAULT NULL CHECK(birthDay IS NULL OR (birthDay >= 1 AND birthDay <= 31)),
    birthCountry VARCHAR(255) DEFAULT NULL,
    deathYear INT(11) DEFAULT NULL CHECK(deathYear IS NULL OR deathYear >= 1851),
    deathMonth INT(11) DEFAULT NULL CHECK(deathMonth IS NULL OR (deathMonth >= 1 AND deathMonth <= 12)),
    deathDay INT(11) DEFAULT NULL CHECK(deathDay IS NULL OR (deathDay >= 1 AND deathDay <= 31)),
    nameFirst VARCHAR(255) DEFAULT NULL,
    nameLast VARCHAR(255) DEFAULT NULL,
    weight INT(11) DEFAULT NULL CHECK(weight IS NULL OR weight > 0),
    height INT(11) DEFAULT NULL CHECK(height IS NULL OR height > 0),
    bats VARCHAR(255) DEFAULT NULL CHECK(bats IS NULL OR bats = 'L' OR bats = 'R' OR bats = 'B'),
    throws VARCHAR(255) DEFAULT NULL CHECK(throws IS NULL OR throws = 'L' OR throws = 'R' OR throws = 'B'),
    debut VARCHAR(255) DEFAULT NULL,
    finalGame VARCHAR(255) DEFAULT NULL,
    bbrefID VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Pitching (
    playerID VARCHAR(9) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    stint SMALLINT(6) NOT NULL CHECK(stint >= 1),
    teamID CHAR(3) NOT NULL,
    leagueID CHAR(2) DEFAULT NULL,
    W SMALLINT(6) DEFAULT NULL CHECK(W IS NULL OR (W >= 0 AND G IS NOT NULL AND W <= G)),
    L SMALLINT(6) DEFAULT NULL CHECK(L IS NULL OR (L >= 0 AAND G IS NOT NULL ND L <= G)),
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    GS SMALLINT(6) DEFAULT NULL CHECK(GS IS NULL OR (GS >= 0 AND G IS NOT NULL AND GS <= G)),
    CG SMALLINT(6) DEFAULT NULL CHECK(CG IS NULL OR (CG >= 0 AND GS IS NOT NULL AND CG <= GS)),
    SHO SMALLINT(6) DEFAULT NULL CHECK(SHO IS NULL OR (SHO >= 0 AND CG IS NOT NULL AND SHO <= CG)),
    SV SMALLINT(6) DEFAULT NULL CHECK(SV IS NULL OR (SV >= 0 AND G IS NOT NULL AND SV <= G)),
    outsRecorded INT(11) DEFAULT NULL CHECK(outsRecorded IS NULL OR outsRecorded >= 0),
    H SMALLINT(6) DEFAULT NULL CHECK(H IS NULL OR H >= 0),
    ER SMALLINT(6) DEFAULT NULL CHECK(ER IS NULL OR ER >= 0),
    HR SMALLINT(6) DEFAULT NULL CHECK(HR IS NULL OR HR >= 0),
    BB SMALLINT(6) DEFAULT NULL CHECK(BB IS NULL OR BB >= 0),
    SO SMALLINT(6) DEFAULT NULL CHECK(SO IS NULL OR SO >= 0),
    BAOpponents double DEFAULT NULL CHECK(BAOpponents IS NULL OR (BAOpponents >= 0 AND BAOpponents <= 1)),
    ERA double DEFAULT NULL CHECK(ERA IS NULL OR ERA >= 0),
    IBB SMALLINT(6) DEFAULT NULL CHECK(IBB IS NULL OR IBB >= 0),
    WP SMALLINT(6) DEFAULT NULL CHECK(WP IS NULL OR WP >= 0),
    HBP SMALLINT(6) DEFAULT NULL CHECK(HBP IS NULL OR HBP >= 0),
    BK SMALLINT(6) DEFAULT NULL CHECK(BK IS NULL OR BK >= 0),
    GF SMALLINT(6) DEFAULT NULL CHECK(GF IS NULL OR (GF >= 0 AND G IS NOT NULL AND GF <= G)),
    R SMALLINT(6) DEFAULT NULL CHECK(R IS NULL OR R >= 0),
    SH SMALLINT(6) DEFAULT NULL CHECK(SH IS NULL OR SH >= 0),
    SF SMALLINT(6) DEFAULT NULL CHECK(SF IS NULL OR SF >= 0),
    GIDP SMALLINT(6) DEFAULT NULL CHECK(GIDP IS NULL OR GIDP >= 0),
    PRIMARY KEY (playerID, yearID, stint),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Teams (
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    leagueID CHAR(2) DEFAULT NULL,
    teamID CHAR(3) NOT NULL,
    franchiseID VARCHAR(3) NOT NULL,
    divisionID CHAR(1) DEFAULT NULL,
    teamRank SMALLINT(6) DEFAULT NULL,
    G SMALLINT(6) DEFAULT NULL CHECK(G IS NULL OR G >= 0),
    gamesAtHome SMALLINT(6) DEFAULT NULL CHECK(gamesAtHome IS NULL OR (gamesAtHome >= 0 AND G IS NOT NULL AND gamesAtHome <= G)),
    W SMALLINT(6) DEFAULT NULL CHECK(W IS NULL OR (W >= 0 AND G IS NOT NULL AND W <= G)),
    L SMALLINT(6) DEFAULT NULL CHECK(L IS NULL OR (L >= 0 AND G IS NOT NULL AND L <= G)),
    divisionWin VARCHAR(1) DEFAULT NULL CHECK(divisionWin IS NULL OR divisionWin = 'Y' OR divisionWin = 'N'),
    wildCardWin VARCHAR(1) DEFAULT NULL CHECK(wildCardWin IS NULL OR wildCardWin = 'Y' OR wildCardWin = 'N'),
    leagueWin VARCHAR(1) DEFAULT NULL CHECK(leagueWin IS NULL OR leagueWin = 'Y' OR leagueWin = 'N'),
    worldSeriesWin VARCHAR(1) DEFAULT NULL CHECK(worldSeriesWin IS NULL OR worldSeriesWin = 'Y' OR worldSeriesWin = 'N'),
    R SMALLINT(6) DEFAULT NULL CHECK(R IS NULL OR R >= 0),
    AB SMALLINT(6) DEFAULT NULL CHECK(AB IS NULL OR AB >= 0),
    H SMALLINT(6) DEFAULT NULL CHECK(H IS NULL OR H >= 0),
    2B SMALLINT(6) DEFAULT NULL CHECK(2B IS NULL OR 2B >= 0),
    3B SMALLINT(6) DEFAULT NULL CHECK(3B IS NULL OR 3B >= 0),
    HR SMALLINT(6) DEFAULT NULL CHECK(HR IS NULL OR HR >= 0),
    BB SMALLINT(6) DEFAULT NULL CHECK(BB IS NULL OR BB >= 0),
    SO SMALLINT(6) DEFAULT NULL CHECK(SO IS NULL OR SO >= 0),
    SB SMALLINT(6) DEFAULT NULL CHECK(SB IS NULL OR SB >= 0),
    CS SMALLINT(6) DEFAULT NULL CHECK(CS IS NULL OR CS >= 0),
    HBP SMALLINT(6) DEFAULT NULL CHECK(HBP IS NULL OR HBP >= 0),
    SF SMALLINT(6) DEFAULT NULL CHECK(SF IS NULL OR SF >= 0),
    RA SMALLINT(6) DEFAULT NULL CHECK(RA IS NULL OR RA >= 0),
    ER SMALLINT(6) DEFAULT NULL CHECK(ER IS NULL OR ER >= 0),
    ERA double DEFAULT NULL CHECK(ERA IS NULL OR ERA >= 0),
    CG SMALLINT(6) DEFAULT NULL CHECK(CG IS NULL OR (CG >= 0 AND G IS NOT NULL AND CG <= G)),
    SHO SMALLINT(6) DEFAULT NULL CHECK(SHO IS NULL OR (SHO >= 0 AND CG IS NOT NULL AND SHO <= CG)),
    SV SMALLINT(6) DEFAULT NULL CHECK(SV IS NULL OR (SV >= 0 AND G IS NOT NULL AND SV <= G)),
    outsRecorded INT(11) DEFAULT NULL CHECK(outsRecorded IS NULL OR outsRecorded >= 0),
    HA SMALLINT(6) DEFAULT NULL CHECK(HA IS NULL OR HA >= 0),
    HRA SMALLINT(6) DEFAULT NULL CHECK(HRA IS NULL OR HRA >= 0),
    BBA SMALLINT(6) DEFAULT NULL CHECK(BBA IS NULL OR BBA >= 0),
    SOA SMALLINT(6) DEFAULT NULL CHECK(SOA IS NULL OR SOA >= 0),
    E INT(11) DEFAULT NULL CHECK(E IS NULL OR E >= 0),
    DP INT(11) DEFAULT NULL CHECK(DP IS NULL OR DP >= 0),
    FP double DEFAULT NULL CHECK(FP IS NULL OR (FP >= 0 AND FP <= 1)),
    name VARCHAR(50) DEFAULT NULL,
    park VARCHAR(255) DEFAULT NULL,
    attendance INT(11) DEFAULT NULL CHECK(attendance IS NULL OR attendance >= 0),
    PRIMARY KEY (yearID, teamID),
    FOREIGN KEY (franchiseID) REFERENCES Franchises(franchiseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Franchises (
    franchiseID VARCHAR(3) NOT NULL,
    franchiseName VARCHAR(50) DEFAULT NULL,
    isActive VARCHAR(2) NOT NULL CHECK(isActive = 'Y' OR isActive = 'N' OR isActive = 'NA'),        /* type change */
    PRIMARY KEY (franchiseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE Users (
    userID VARCHAR(50) NOT NULL,
    nameFirst VARCHAR(255) NOT NULL,
    nameLast VARCHAR(255) NOT NULL,
    pwd VARCHAR(50) NOT NULL,
    PRIMARY KEY (userID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE FavouriteFranchises (
    userID VARCHAR(50) NOT NULL,
    franchiseID VARCHAR(3) NOT NULL,
    PRIMARY KEY (userID, franchiseID),
    FOREIGN KEY (userID) REFERENCES Users(userID),
    FOREIGN KEY (franchiseID) REFERENCES Franchises(franchiseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE FavouriteTeams (
    userID VARCHAR(50) NOT NULL,
    yearID SMALLINT(6) NOT NULL CHECK(yearID >= 1871),
    teamID CHAR(3) NOT NULL,
    PRIMARY KEY (userID, yearID, teamID),
    FOREIGN KEY (userID) REFERENCES Users(userID),
    FOREIGN KEY (yearID, teamID) REFERENCES Teams(yearID, teamID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE FavouritePlayers (
    userID VARCHAR(50) NOT NULL,
    playerID VARCHAR(9) NOT NULL,
    PRIMARY KEY (userID, playerID),
    FOREIGN KEY (userID) REFERENCES Users(userID),
    FOREIGN KEY (playerID) REFERENCES Players(playerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
